(package "newline-dwim"
         "0.0.1"
         "Insert a newline and DWIM characters")

(website-url "https://github.com/emacs-php/newline-dwim")
(keywords "convenience")

(package-file "newline-dwim.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "25.1")
(depends-on "cl-lib" "0.5")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
